/**
 * The words a generated credential is drawn from (story 7.8): 2048 common
 * Croatian words of three to six letters, `a`–`z` only.
 *
 * WHY 2048. It is 2^11, so each word takes exactly eleven bits of a 16-bit
 * draw with no bias and no rejection (`password.ts`). The length is asserted,
 * not assumed: `test/admin-auth-boundary.test.ts` holds it at 2048, every word
 * unique and of the shape, and no two words one final vowel apart.
 *
 * WHAT IS LEFT OUT, and why each rule is about the phone call this credential
 * is read out in: no `č ć š ž đ` (a keyboard and a spoken letter disagree too
 * often); no near-duplicates such as `kuca`/`kuce` (two inflections of one word
 * are one word said twice); nothing offensive, morbid or a proper name.
 *
 * Sorted, so a diff to the list reads as the words that changed.
 */
export const WORDS: readonly string[] = [
  'adresa', 'adut', 'agava', 'ajvar', 'akcent', 'akcija', 'akord', 'alarm', 'alat', 'album',
  'aleja', 'alga', 'alka', 'aloja', 'alpaka', 'alpski', 'amater', 'ambar', 'amblem', 'amfora',
  'amulet', 'ananas', 'anis', 'anketa', 'anorak', 'antena', 'antika', 'aparat', 'apel', 'apetit',
  'aplauz', 'arena', 'arhiva', 'arija', 'aroma', 'artikl', 'asfalt', 'aspekt', 'astra', 'atelje',
  'atlas', 'atlet', 'atol', 'atom', 'atrij', 'auto', 'autor', 'avans', 'avion', 'azur', 'babun',
  'baciti', 'badem', 'bager', 'bagrem', 'bajka', 'baka', 'bakar', 'baklja', 'bal', 'balada',
  'balet', 'balkon', 'balon', 'balvan', 'balzam', 'bambus', 'banana', 'banka', 'bankar', 'bara',
  'barjak', 'barka', 'barmen', 'barok', 'barun', 'bas', 'basist', 'basna', 'batana', 'baviti',
  'baza', 'bazar', 'bazen', 'bazga', 'beba', 'bedem', 'bedro', 'bend', 'berba', 'beton', 'bicikl',
  'bife', 'bijeg', 'bijel', 'bik', 'biljar', 'bilje', 'biljeg', 'biljka', 'bina', 'biolog', 'biro',
  'biser', 'bista', 'bistar', 'bistro', 'bitan', 'biti', 'bivak', 'bivol', 'bizon', 'blag',
  'blato', 'blijed', 'blitva', 'blizak', 'blizu', 'blok', 'bluza', 'boa', 'bob', 'bobica', 'boca',
  'bod', 'bodar', 'bodlja', 'bogat', 'boja', 'bojica', 'bojiti', 'bojler', 'bok', 'bokal', 'boks',
  'bolid', 'bombon', 'bonaca', 'bonus', 'bor', 'bordo', 'bova', 'brada', 'brana', 'branik',
  'brati', 'brava', 'bravar', 'brazda', 'brdo', 'breza', 'brid', 'briga', 'brijeg', 'britva',
  'brk', 'brlog', 'brod', 'brodar', 'brodet', 'broj', 'brojka', 'bronca', 'brus', 'brvno', 'brz',
  'brzina', 'buba', 'bubanj', 'budan', 'buditi', 'buha', 'bujan', 'bujica', 'buka', 'buket',
  'bukva', 'bumbar', 'bunar', 'bunda', 'buran', 'bure', 'burek', 'burza', 'busen', 'but', 'butik',
  'buzara', 'car', 'carina', 'cedar', 'celer', 'cement', 'centar', 'cer', 'cerada', 'cesta',
  'cifra', 'cigla', 'cijelo', 'cijena', 'cijev', 'cikla', 'ciklus', 'cilj', 'cimer', 'cimet',
  'cink', 'cipal', 'cipela', 'cirkus', 'citat', 'citra', 'citrus', 'cjenik', 'crijep', 'crn',
  'crpka', 'crta', 'crtati', 'crv', 'crven', 'cvat', 'cvijet', 'dabar', 'dagnja', 'dah', 'dalek',
  'dalija', 'dama', 'dan', 'danas', 'dar', 'dariti', 'daska', 'dati', 'datum', 'davati', 'debata',
  'deblo', 'deka', 'dekor', 'dekret', 'delfin', 'delta', 'derbi', 'desert', 'deset', 'desno',
  'detalj', 'deva', 'devet', 'dijete', 'diktat', 'dim', 'dinar', 'dingo', 'dinja', 'dio', 'dioda',
  'dirati', 'disati', 'disk', 'div', 'divan', 'dizajn', 'dizalo', 'dizati', 'djed', 'djelo',
  'dlaka', 'dlan', 'dnevni', 'dno', 'dob', 'dobar', 'dobit', 'dobro', 'dodati', 'dodir', 'dojam',
  'dokaz', 'doktor', 'dolar', 'dolina', 'dolje', 'dom', 'domar', 'domet', 'domino', 'donji',
  'dopis', 'dopust', 'dosta', 'drag', 'drama', 'dres', 'drijen', 'drmati', 'dron', 'drozd', 'drug',
  'drugar', 'drvar', 'drvce', 'drven', 'drvo', 'dubina', 'dubok', 'duet', 'duga', 'duh', 'dukat',
  'dunja', 'dupin', 'dva', 'dvojka', 'dvopek', 'dvor', 'dvorac', 'efekt', 'ekipa', 'ekonom',
  'ekran', 'elan', 'elisa', 'emajl', 'emu', 'enigma', 'epilog', 'epoha', 'era', 'esej', 'etapa',
  'etika', 'fagot', 'far', 'farma', 'fasada', 'fauna', 'faza', 'fazan', 'fen', 'fenjer', 'feta',
  'figura', 'fikus', 'filc', 'filet', 'film', 'filter', 'finale', 'firma', 'fitilj', 'fizika',
  'fjord', 'flauta', 'flora', 'flota', 'foka', 'fokus', 'folija', 'fond', 'forma', 'forte',
  'fosil', 'frak', 'fraza', 'freska', 'frizbi', 'frizer', 'frula', 'furnir', 'gaj', 'gajde',
  'gajeta', 'gakati', 'galeb', 'galija', 'galop', 'gasiti', 'gat', 'gavran', 'gaza', 'gazda',
  'gazela', 'gaziti', 'gejzir', 'gem', 'genij', 'geodet', 'geolog', 'gepard', 'geslo', 'gesta',
  'gibak', 'gibati', 'gibon', 'gips', 'gitara', 'gladak', 'gladan', 'glagol', 'glas', 'glasan',
  'glava', 'glavni', 'glazba', 'glib', 'glina', 'glinen', 'glista', 'gljiva', 'globus', 'glog',
  'glumac', 'gmaz', 'gnom', 'godina', 'gol', 'golem', 'golf', 'golman', 'golub', 'gong', 'gora',
  'gorak', 'gord', 'gorila', 'gornji', 'gorski', 'gost', 'gotov', 'govor', 'gozba', 'grab', 'grad',
  'graf', 'grafit', 'grah', 'grana', 'granit', 'grb', 'greben', 'greda', 'grimiz', 'gristi',
  'griva', 'griz', 'grlica', 'grliti', 'grm', 'grom', 'grozd', 'grub', 'gruda', 'grudva', 'grupa',
  'gubiti', 'guma', 'gumb', 'gumica', 'gumno', 'gurati', 'guska', 'gusle', 'gust', 'gutati',
  'hala', 'hangar', 'harfa', 'heljda', 'heroj', 'hijena', 'himna', 'hir', 'hit', 'hitan', 'hitar',
  'hlad', 'hladan', 'hmelj', 'hobi', 'hod', 'hodati', 'hodnik', 'hokej', 'hotel', 'hrabar',
  'hrana', 'hrapav', 'hrast', 'hrbat', 'hren', 'hrid', 'hrkati', 'hrpa', 'hrskav', 'htjeti',
  'hukati', 'humak', 'humor', 'humus', 'ibis', 'ideja', 'idila', 'igla', 'igra', 'igrati',
  'igrica', 'ikona', 'ikra', 'imanje', 'imati', 'ime', 'imela', 'imenik', 'impala', 'indeks',
  'inje', 'iris', 'ishod', 'iskra', 'iskren', 'ispit', 'ispod', 'ispuh', 'isti', 'istina', 'istok',
  'iver', 'izba', 'izbor', 'izdah', 'izlaz', 'izlet', 'izlog', 'iznad', 'iznos', 'izraz', 'izreka',
  'izum', 'izuti', 'izvod', 'izvor', 'izvoz', 'jablan', 'jabuka', 'jagoda', 'jaguar', 'jahati',
  'jahta', 'jaje', 'jak', 'jakna', 'jakost', 'jama', 'janje', 'jantar', 'jarac', 'jarak', 'jaram',
  'jarbol', 'jare', 'jaruga', 'jasan', 'jasen', 'jasika', 'jasle', 'jasmin', 'jastog', 'jastuk',
  'jato', 'javan', 'javiti', 'javor', 'jedan', 'jedar', 'jednak', 'jedro', 'jeftin', 'jeka',
  'jela', 'jelen', 'jesen', 'jesti', 'jezero', 'jezgra', 'jezik', 'joga', 'jogurt', 'joha', 'judo',
  'jugo', 'juha', 'junac', 'junak', 'jutro', 'kabel', 'kabina', 'kada', 'kadar', 'kadifa', 'kajak',
  'kajmak', 'kakadu', 'kakao', 'kaki', 'kaktus', 'kala', 'kalem', 'kalina', 'kalup', 'kamen',
  'kamera', 'kamin', 'kamion', 'kamp', 'kampus', 'kanal', 'kanjon', 'kanta', 'kanu', 'kap',
  'kapak', 'kapati', 'kapela', 'kapija', 'kaput', 'karate', 'karika', 'karta', 'karton', 'kaseta',
  'kasno', 'kat', 'katran', 'kava', 'kavez', 'kazan', 'kebab', 'kefir', 'kegla', 'keks', 'kelj',
  'kemija', 'kesten', 'kidati', 'kifla', 'kihati', 'kim', 'kimati', 'kino', 'kiosk', 'kip',
  'kipar', 'kirurg', 'kiseo', 'kisik', 'kist', 'kit', 'kititi', 'kivi', 'klanac', 'klapa', 'klas',
  'klaun', 'klavir', 'klen', 'kliker', 'klima', 'klin', 'klip', 'kljun', 'klompa', 'klub', 'klupa',
  'klupko', 'knedla', 'knez', 'knjiga', 'koala', 'kobac', 'kobalt', 'kobila', 'kobra', 'kocka',
  'kofer', 'kojot', 'kokice', 'kokos', 'kokot', 'kokpit', 'kola', 'kolega', 'koliba', 'kolnik',
  'kolona', 'kolut', 'komad', 'kombi', 'komet', 'komin', 'komoda', 'komora', 'kompas', 'kompot',
  'konac', 'kondor', 'konj', 'konjic', 'konoba', 'konop', 'kopar', 'kopati', 'kopija', 'kopito',
  'kopno', 'kora', 'korak', 'koralj', 'korica', 'korito', 'korner', 'korov', 'korpa', 'korzo',
  'kosa', 'kositi', 'kosmos', 'kost', 'kostim', 'kotao', 'kotar', 'kotlet', 'kotur', 'kovati',
  'koza', 'kozica', 'krafna', 'kragna', 'kraj', 'krak', 'kralj', 'kran', 'krasan', 'kratak',
  'krater', 'krava', 'krdo', 'kreda', 'krema', 'kremen', 'krevet', 'krhak', 'krigla', 'krilo',
  'kriti', 'krma', 'kroj', 'krov', 'kroz', 'krpa', 'krpelj', 'krtica', 'krug', 'kruh', 'kruna',
  'krupan', 'krut', 'krzno', 'kubik', 'kudrav', 'kugla', 'kuhan', 'kuhar', 'kuhati', 'kuk', 'kula',
  'kulen', 'kulisa', 'kum', 'kuna', 'kup', 'kupac', 'kupati', 'kupina', 'kupiti', 'kupka',
  'kupola', 'kupon', 'kupus', 'kurir', 'kursor', 'kustos', 'kut', 'kutak', 'kutija', 'kutnik',
  'kvadar', 'kvaka', 'kvart', 'kvasac', 'kviz', 'kvrgav', 'labud', 'ladica', 'lagan', 'laguna',
  'lahor', 'lajati', 'lak', 'lakat', 'lala', 'lama', 'lampa', 'lanac', 'lane', 'laser', 'lasica',
  'laso', 'lasta', 'latica', 'lav', 'lavica', 'lavina', 'lavor', 'led', 'leden', 'lediti',
  'legato', 'leglo', 'lemur', 'lepeza', 'leptir', 'let', 'letak', 'letva', 'libela', 'lice',
  'lift', 'liga', 'lignja', 'lijeha', 'lijek', 'lijep', 'lijevo', 'lik', 'liker', 'lim', 'limar',
  'limeta', 'limun', 'linija', 'lipa', 'lipanj', 'lira', 'lisica', 'lisnat', 'list', 'liti',
  'litica', 'litra', 'livada', 'lizati', 'ljetni', 'ljeto', 'ljubak', 'ljubav', 'ljuska', 'ljut',
  'logika', 'lokal', 'lokot', 'lokva', 'lomiti', 'lonac', 'lopar', 'lopata', 'lopta', 'los',
  'losos', 'lotos', 'lov', 'lovac', 'loviti', 'lovor', 'loza', 'lubin', 'lugar', 'luk', 'lukav',
  'lupa', 'lupati', 'lupina', 'luster', 'lutati', 'lutka', 'lutnja', 'madrac', 'magla', 'magma',
  'magnet', 'mah', 'mahati', 'mahuna', 'majica', 'majka', 'majmun', 'mak', 'maketa', 'makija',
  'malen', 'malina', 'malo', 'mama', 'mamac', 'mamiti', 'mango', 'manta', 'mantil', 'mapa',
  'marama', 'marina', 'marka', 'maser', 'masiv', 'maska', 'maslac', 'mast', 'matica', 'matura',
  'mazati', 'mazga', 'maziti', 'mazivo', 'med', 'meden', 'meduza', 'mek', 'mekan', 'melem',
  'mentor', 'menza', 'mesar', 'mesnat', 'mesni', 'meso', 'mesti', 'meta', 'metal', 'metar',
  'metla', 'metoda', 'metro', 'migati', 'mijena', 'mikser', 'milina', 'milja', 'milost', 'mimoza',
  'minuta', 'mio', 'mir', 'miran', 'miris', 'mirta', 'misao', 'mit', 'mjed', 'mjehur', 'mjera',
  'mjesec', 'mjesto', 'mlad', 'mlak', 'mlaz', 'mlin', 'mlinar', 'mljeti', 'moda', 'modar', 'model',
  'modul', 'mokar', 'mol', 'molba', 'moliti', 'momak', 'monter', 'moped', 'more', 'mornar',
  'morski', 'most', 'motati', 'motel', 'motika', 'motiv', 'motka', 'motor', 'mozaik', 'mozak',
  'mramor', 'mrav', 'mraz', 'mrk', 'mrkva', 'mrlja', 'mrvica', 'mudar', 'muflon', 'muha', 'mukati',
  'mula', 'mulj', 'munja', 'mutan', 'mutiti', 'muzej', 'nada', 'nafta', 'nagib', 'naivan', 'nakit',
  'naklon', 'nakon', 'namaz', 'napor', 'nar', 'narav', 'narcis', 'narod', 'nasip', 'naslov',
  'nastup', 'nasuti', 'natpis', 'natrag', 'nauka', 'navala', 'navika', 'navoj', 'naziv', 'nebo',
  'negdje', 'nekad', 'nektar', 'neon', 'nesti', 'neven', 'nigdje', 'nikad', 'nisa', 'nit', 'niz',
  'nizak', 'nizati', 'nizina', 'njiva', 'njoki', 'njuh', 'noga', 'noj', 'nokat', 'norma', 'nos',
  'nositi', 'nota', 'notar', 'notes', 'nov', 'novac', 'novela', 'novina', 'novost', 'nuditi',
  'nula', 'oaza', 'obad', 'obala', 'obilan', 'objed', 'oblak', 'oblik', 'oboa', 'obod', 'obrana',
  'obraz', 'obris', 'obrok', 'obrt', 'obrva', 'obuka', 'obuti', 'obzir', 'obzor', 'ocean',
  'ocelot', 'oda', 'odan', 'odgoj', 'odjek', 'odjel', 'odluka', 'odmah', 'odmor', 'odnos', 'odraz',
  'odsjaj', 'odsjek', 'oglas', 'ograda', 'ogrozd', 'okapi', 'oker', 'oklada', 'okno', 'oko',
  'okret', 'okrug', 'oktava', 'okuka', 'okus', 'okvir', 'olovka', 'olovo', 'oluja', 'omara',
  'omjer', 'omlet', 'omot', 'opal', 'opeka', 'opera', 'opet', 'opis', 'oposum', 'oprati', 'oprema',
  'opruga', 'opseg', 'orada', 'orah', 'oran', 'orao', 'orati', 'orbita', 'orka', 'orkan', 'ormar',
  'osa', 'osam', 'oseka', 'osmica', 'osnova', 'osvrt', 'otac', 'otisak', 'otok', 'otpor', 'otvor',
  'oval', 'ovan', 'ovca', 'ovdje', 'ozon', 'pak', 'paket', 'palac', 'paleta', 'palica', 'paliti',
  'palma', 'paluba', 'pamet', 'pamuk', 'panda', 'panel', 'panj', 'papaja', 'papak', 'papar',
  'papiga', 'papir', 'paprat', 'para', 'parada', 'parfem', 'park', 'parket', 'pas', 'pasara',
  'pasta', 'pastel', 'pastir', 'patent', 'patka', 'pauk', 'paun', 'pauza', 'paziti', 'pecivo',
  'pedala', 'pegla', 'pehar', 'pekara', 'pekmez', 'pelena', 'pelin', 'pelud', 'penal', 'pepeo',
  'peraja', 'perje', 'perla', 'pero', 'peron', 'peta', 'petak', 'petero', 'petlja', 'piano',
  'pijuk', 'pikado', 'piknik', 'pile', 'piliti', 'pilot', 'pinjol', 'pionir', 'pipa', 'pirana',
  'pire', 'pisac', 'pisati', 'pismo', 'pista', 'pita', 'pitati', 'piton', 'pivar', 'pivo', 'pjega',
  'pjegav', 'pjena', 'pjesma', 'plah', 'plahta', 'plakat', 'plamen', 'plan', 'planet', 'plast',
  'platno', 'plato', 'plav', 'pleme', 'ples', 'plesac', 'plesti', 'plima', 'plin', 'plitak',
  'plod', 'plodan', 'ploha', 'plovak', 'plug', 'pluto', 'pobuda', 'pod', 'podij', 'podne',
  'podrum', 'poema', 'poen', 'pogled', 'pogon', 'pojam', 'pojas', 'pojilo', 'pojiti', 'pokal',
  'poklon', 'pokret', 'pokrov', 'pokus', 'pol', 'polako', 'polet', 'polica', 'polje', 'polka',
  'poluga', 'pomak', 'ponij', 'ponor', 'ponos', 'ponuda', 'popis', 'popiti', 'poplun', 'popust',
  'porast', 'pored', 'portal', 'portir', 'porub', 'poruka', 'posao', 'posjet', 'pospan', 'poster',
  'posuda', 'posuti', 'potez', 'potok', 'povod', 'poziv', 'poznat', 'prag', 'prah', 'pramac',
  'pramen', 'prase', 'prati', 'pravda', 'prazan', 'predah', 'predio', 'prekid', 'preko', 'prema',
  'presti', 'pribor', 'prije', 'prijem', 'prikaz', 'prilaz', 'prilog', 'princ', 'prinos', 'pritok',
  'prizma', 'prizor', 'proba', 'prodor', 'prolaz', 'prolog', 'prorez', 'proso', 'proza', 'prozor',
  'prsluk', 'prst', 'prsten', 'pruga', 'prut', 'ptica', 'puder', 'puding', 'pudla', 'puh',
  'puhati', 'pulpa', 'puls', 'puma', 'pumpa', 'pun', 'puniti', 'pupak', 'puran', 'purica',
  'purpur', 'pust', 'put', 'putnik', 'rad', 'radar', 'radin', 'radio', 'raditi', 'radnik',
  'radnja', 'radost', 'ragbi', 'ragu', 'raketa', 'rakun', 'ralica', 'rame', 'rampa', 'rang',
  'rano', 'rast', 'ratar', 'ravan', 'razina', 'razlog', 'razred', 'razum', 'razvoj', 'rebro',
  'rebus', 'recept', 'red', 'redak', 'redar', 'refren', 'regal', 'regata', 'regija', 'reket',
  'rekord', 'reljef', 'remen', 'remi', 'rep', 'repat', 'revija', 'rez', 'rezati', 'riba', 'ribar',
  'ribica', 'ribiz', 'riblji', 'rijeka', 'rikati', 'rima', 'ring', 'ris', 'ritam', 'rizoto',
  'roba', 'robot', 'roda', 'rodak', 'rodan', 'rog', 'rogoz', 'roj', 'rok', 'roleta', 'roman',
  'roniti', 'rosa', 'rotkva', 'rotor', 'rozeta', 'rub', 'rubac', 'rubin', 'rublje', 'rubnik',
  'ruda', 'rudnik', 'ruho', 'rujan', 'ruka', 'rukav', 'rukola', 'ruksak', 'rumba', 'rumen',
  'runda', 'runo', 'rupa', 'ruta', 'rzanje', 'rzati', 'sabor', 'sada', 'saditi', 'safari', 'safir',
  'saga', 'sajam', 'sako', 'salama', 'salata', 'salon', 'salpa', 'salsa', 'salto', 'sam', 'samba',
  'san', 'sanduk', 'sanjar', 'sanjke', 'santa', 'sapun', 'sarma', 'sastav', 'sat', 'satara',
  'saten', 'sauna', 'savana', 'savez', 'saviti', 'savjet', 'scena', 'sedam', 'sedef', 'sedlo',
  'sedra', 'sektor', 'seliti', 'seljak', 'selo', 'senf', 'senzor', 'seoski', 'sepija', 'serija',
  'servis', 'sestar', 'sestra', 'set', 'sezam', 'sezona', 'sfera', 'sidro', 'sifon', 'signal',
  'sijati', 'sijeno', 'silos', 'simbol', 'sin', 'singl', 'sinuti', 'sipa', 'sir', 'sirak', 'sirar',
  'sirena', 'sirov', 'sirup', 'sitan', 'sito', 'siv', 'sjaj', 'sjajan', 'sjati', 'sjeme', 'sjena',
  'sjenik', 'sjenka', 'sjesti', 'sjetva', 'sjever', 'skala', 'skela', 'skener', 'skica', 'skija',
  'sklad', 'sklon', 'skok', 'skup', 'skuta', 'skuter', 'slab', 'sladak', 'slalom', 'slama',
  'slamka', 'slan', 'slanje', 'slap', 'slast', 'slati', 'slava', 'slavan', 'slavuj', 'slijed',
  'slika', 'slikar', 'sljez', 'sloga', 'slogan', 'sloj', 'slon', 'slovo', 'sluh', 'smijeh',
  'smion', 'smiren', 'smisao', 'smjena', 'smjer', 'smjesa', 'smjeti', 'smokva', 'smola', 'smreka',
  'snaga', 'snaha', 'snijeg', 'snop', 'soba', 'sofa', 'soja', 'sok', 'sokol', 'sol', 'solist',
  'soliti', 'som', 'sonar', 'sonda', 'sonet', 'sopila', 'sopran', 'sorta', 'sova', 'spas',
  'spiker', 'splav', 'splet', 'spoj', 'spojka', 'spokoj', 'spomen', 'spor', 'sport', 'sprava',
  'sprint', 'sprud', 'spust', 'srce', 'srdela', 'srebrn', 'srebro', 'sretan', 'srkati', 'srna',
  'srp', 'srpanj', 'stablo', 'stado', 'staja', 'staklo', 'stakor', 'stalak', 'stalan', 'stan',
  'stanje', 'star', 'starac', 'start', 'stati', 'stativ', 'statua', 'stav', 'staza', 'stepa',
  'stih', 'stil', 'sto', 'stog', 'stoka', 'stol', 'stolar', 'stopa', 'strana', 'streha', 'stric',
  'strm', 'strofa', 'strog', 'stroj', 'strop', 'struja', 'struk', 'studen', 'studio', 'subota',
  'sud', 'sudac', 'sufiks', 'suh', 'suknja', 'sumrak', 'sunce', 'sup', 'susjed', 'susret',
  'sustav', 'suton', 'sutra', 'suza', 'svadba', 'svat', 'svemir', 'svijet', 'svila', 'svilen',
  'svirka', 'svitak', 'svod', 'svraka', 'svrdlo', 'svrha', 'taban', 'tabla', 'tabor', 'tajna',
  'tajnik', 'taksi', 'takt', 'talent', 'taliti', 'talog', 'tama', 'taman', 'tanak', 'tango',
  'tanjur', 'tapeta', 'tapir', 'tartuf', 'tata', 'tava', 'tavan', 'teatar', 'tegla', 'tekst',
  'tele', 'tema', 'temelj', 'tempo', 'tenda', 'tenis', 'tenor', 'tepih', 'terasa', 'teren',
  'teret', 'termin', 'termit', 'termos', 'tesar', 'tesati', 'test', 'teta', 'tetak', 'teza',
  'tezga', 'tigar', 'tih', 'tijelo', 'tikva', 'tim', 'timpan', 'tinta', 'tipka', 'tirkiz', 'tisa',
  'tisak', 'tiskar', 'titula', 'tjedan', 'tjedni', 'tjeme', 'tkati', 'tlak', 'tlo', 'tok', 'tokar',
  'ton', 'tonuti', 'topao', 'topiti', 'topola', 'topot', 'tor', 'toranj', 'torba', 'torta', 'tost',
  'toster', 'trag', 'trajan', 'traka', 'trasa', 'trava', 'travar', 'travka', 'trbuh', 'tren',
  'trend', 'trener', 'treset', 'tresti', 'trezor', 'trg', 'trgati', 'tri', 'trijem', 'trik',
  'trio', 'trka', 'trn', 'trnina', 'trofej', 'trojka', 'trokut', 'trom', 'trp', 'trpeza', 'trsje',
  'trska', 'truba', 'trud', 'trup', 'tuba', 'tucet', 'tuga', 'tukan', 'tuljan', 'tulum', 'tuna',
  'tundra', 'tunel', 'tunika', 'tup', 'turnir', 'tvar', 'tvor', 'tvrd', 'ubrati', 'ubrus', 'udica',
  'udio', 'udoban', 'udruga', 'uglat', 'ugled', 'ugljen', 'ugodan', 'ugovor', 'uho', 'ujak',
  'ukras', 'ukus', 'ular', 'ulaz', 'ulica', 'uliti', 'ulje', 'uloga', 'ulov', 'umak', 'umor',
  'unos', 'unuk', 'unutra', 'upit', 'uprava', 'urar', 'ured', 'uredan', 'uredba', 'urlati', 'urod',
  'usjek', 'usjev', 'usluga', 'usna', 'uspjeh', 'uspon', 'usta', 'ustati', 'ustav', 'usuti',
  'uteg', 'utisak', 'utorak', 'utrka', 'utvrda', 'uvala', 'uvesti', 'uvez', 'uvid', 'uvijek',
  'uvod', 'uzda', 'uzeti', 'uzlet', 'uzorak', 'uzoran', 'uzrok', 'vaga', 'vagati', 'vagon', 'val',
  'valcer', 'valjak', 'valjan', 'valuta', 'vani', 'vapno', 'variti', 'varivo', 'vatra', 'vatren',
  'vaza', 'vedar', 'velik', 'ventil', 'veo', 'vepar', 'veseo', 'veslo', 'vesta', 'veza', 'vezati',
  'vezica', 'vic', 'video', 'vidik', 'vidra', 'vijak', 'vijek', 'vijest', 'vika', 'vikati',
  'vikend', 'vila', 'vilica', 'vinar', 'vino', 'vir', 'viriti', 'visina', 'visok', 'vitak',
  'vitez', 'vitlo', 'vizija', 'vjedro', 'vjera', 'vjeran', 'vjetar', 'vlak', 'vlasac', 'voda',
  'voditi', 'vol', 'volan', 'volja', 'voljan', 'vosak', 'voziti', 'vrabac', 'vrana', 'vrata',
  'vratar', 'vrba', 'vrelo', 'vreti', 'vrganj', 'vrh', 'vrhnje', 'vrlo', 'vrpca', 'vrsta', 'vrt',
  'vrtlar', 'vrtlog', 'vuga', 'vuk', 'vulkan', 'vuna', 'vunen', 'zabava', 'zabiti', 'zabuna',
  'zadnji', 'zahod', 'zaklon', 'zakon', 'zaliti', 'zaljev', 'zamah', 'zanat', 'zanos', 'zapad',
  'zapis', 'zarada', 'zaslon', 'zastor', 'zasun', 'zavoj', 'zbirka', 'zbog', 'zbor', 'zbroj',
  'zdenac', 'zdjela', 'zdrav', 'zebra', 'zec', 'zelen', 'zemlja', 'zenit', 'zglob', 'zgoda',
  'zgodan', 'zgrada', 'zid', 'zidar', 'zidati', 'zima', 'zimski', 'zlatan', 'zlatar', 'zmaj',
  'zmija', 'znak', 'znalac', 'znanje', 'znati', 'znoj', 'zob', 'zona', 'zora', 'zrak', 'zrcalo',
  'zreo', 'zrno', 'zub', 'zubar', 'zujati', 'zumbul', 'zvati', 'zvijer', 'zvonar', 'zvonik',
  'zvono', 'zvrk', 'zvuk',
];
